---
- name: Deploy Go-app on eks cluster
  hosts: localhost
  become: true  
  tasks:
    - name: Get cluster identity
      command: "aws sts get-caller-identity"
      register: docker_apply_eks

    - name: Get the kube config to local directory
      command: "aws eks update-kubeconfig --name {{cluster_name}}"
      register: docker_apply_eks_kube

    - name: Find Arn fpr instance role
      shell: aws iam get-role --role-name terraform-eks-{{cluster_name}}-node | jq -r  '.Role.Arn'
      register: clusterarn

    - name: set cluster arn variable
      set_fact: 
        clusterarn: "{{clusterarn}}"

    - name: Apply aws-auth to eks cluster
      command: "kubectl apply -f aws-auth.yaml"

    - name: Apply calico to eks cluster
      command: "kubectl apply -f {{playbook_dir}}/calico.yaml"

    - name: Create cluster role
      command: "kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default"

    - name: Add Docker registry secrets
      command: "kubectl create secret docker-registry regsitrykey --docker-server=https://hub.docker.com --docker-username=naveenvemuri9 --docker-password=NavIN@4779 --docker-email=vemnaveen07@gmail.com" 

    - name: Deploy go-app onto eks cluster
      command: "kubectl apply -f {{playbook_dir}}/go-app/go-app.yaml"

    - name: enable autoscalling
      command: "kubectl autoscale rs go-app --min=2 --max=5 --cpu-percent=80"      


