---
- name: Destroy Kuberntes eks cluster in aws
  hosts: localhost
  become: true
  vars:
      cluster_home: /
      cluster_name: "{{ cluster_name }}"
  tasks:
    - name: Log into DockerHub
      become: true
      docker_login:
         username: naveenvemuri9
         password: NavIN@4779
         email: vemnaveen07@gmail.com

    - name: Terraform init {{cluster_name}} cluster
      become: true   
      docker_container:
         name: "terraform-init-{{cluster_name}}"
         image: naveenvemuri9/awscli-terraform-kubectl
         detach: false
         privileged: yes
         volumes: 
           - "{{cluster_home}}:/{{cluster_name}}:z"         
         command: "terraform init -input=false -var 'name={{cluster_name}}' -no-color ."
      register: terraform_init_container

    - name: Terraform destroy {{cluster_name}} cluster
      debug:
        msg:  "{{ terraform_init_container.ansible_facts.docker_container.Output }}"
    - name: Terraform init {{cluster_name}} cluster
      become: true   
      docker_container:
         name: "terraform-init-{{cluster_name}}"
         image: naveenvemuri9/awscli-terraform-kubectl
         detach: false
         privileged: yes
         volumes: 
           - "{{cluster_home}}:/{{cluster_name}}:z"         
         command: "terraform destroy -force -input=false -var 'name={{cluster_name}}' -auto-approve -no-color ."
      register: terraform_destroy_container

    - name: display Terraform destroy {{cluster_name}} cluster
      debug:
        msg:  "{{ terraform_destroy_container.ansible_facts.docker_container.Output }}"

 
