---
- name: Provision Kuberntes eks cluster in aws
  hosts: localhost
  become: true
  roles:
    - cluster_state    
  tasks:
    - name: Copy terraform scripts to {{cluster_home}}
      copy:
        src: "{{playbook_dir}}/terraform"
        dest: "{{cluster_home}}/"
        force: true

    - name: Terraform init {{cluster_name}} cluster
      become: true
      docker_container:
         name: "terraform-init-{{cluster_name}}"
         image: naveenvemuri9/eks-terraform-cli-amazing
         working_dir: "/{{cluster_name}}"
         detach: false
         privileged: yes
         volumes:
           - "{{cluster_home}}:/{{cluster_name}}:z"
         command: "terraform init -input=false -var 'name={{cluster_name}}' -no-color /{{cluster_name}}/terraform"
      register: terraform_init_container

    - name: display Terraform init {{cluster_name}} cluster
      debug:
        msg:  "{{ terraform_init_container.ansible_facts.docker_container.Output }}"
    
    - name: Destroy {{cluster_name}} cluster
      become: true    
      docker_container:
         name: "terraform-init-{{cluster_name}}"
         image: naveenvemuri9/eks-terraform-cli-amazing
         working_dir: "/{{cluster_name}}"
         detach: false
         privileged: yes
         volumes: 
           - "{{cluster_home}}:/{{cluster_name}}:z"
         command: "terraform destroy -force -var 'name={{cluster_name}}' -auto-approve -no-color /{{cluster_name}}/terraform"
      register: terraform_destroy_container

    - name: display Destroy {{cluster_name}} cluster ID
      debug:
        msg:  "{{ terraform_destroy_container.ansible_facts.docker_container.Output }}"
